#ifndef ALS_DIMMER_I2C_PWM_OUTPUT_HPP
#define ALS_DIMMER_I2C_PWM_OUTPUT_HPP

#include "als-dimmer/interfaces.hpp"
#include <cstdint>
#include <memory>
#include <string>

namespace als_dimmer {

/**
 * I2CPwmOutput - drive a backlight whose dimming PWM is generated by an
 * I2C slave device (e.g. the i2c-tiny-usb-pwm Digispark dongle: virtual
 * slave at 0x77, register 0x00 = 8-bit duty, register 0x01 = enable).
 *
 * Differences from BoePwmOutput (the GPIO+PWM variant):
 *   - PWM is generated OFF the Pi: duty written to a single I2C register.
 *     No /sys/class/pwm export, no pinctrl, no Pi GPIO involvement.
 *   - Same I2C bus typically also hosts the MPQ3367 LED driver at 0x38.
 *     The kernel I2C subsystem serializes transactions on the bus, so this
 *     class talks to both 0x77 and 0x38 over the same fd.
 *
 * On init():
 *   1. Open the I2C device.
 *   2. Unless skip_chip_config is set, configure the MPQ3367 LED driver
 *      at slave 0x38 the same way BoePwmOutput does (regs 0x00=0xA6,
 *      0x01=0xAA, double-read 0x02 to clear the FT_LEDO power-on latch).
 *   3. Write the i2c-tiny-usb-pwm enable register (default 0x01 <- 0x01).
 *      This is idempotent and protects against a daemon restart finding
 *      the dongle in some unexpected disabled state.
 *
 * On setBrightness(0..100):
 *   - Scale to native (default 0..255 for 8-bit).
 *   - Write [duty_register, native_value] to the PWM slave.
 *   - Skip the I2C write if the cached brightness hasn't changed.
 *
 * The dongle's hardware default at power-on is 50% duty + enabled, so the
 * panel comes up briefly at half-bright before the daemon's first
 * setBrightness call. Acceptable - the gap is just USB enumeration plus
 * daemon startup, typically under a second.
 */
class I2CPwmOutput : public OutputInterface {
public:
    I2CPwmOutput(const std::string& device,
                 uint8_t address,
                 uint8_t duty_register,
                 uint8_t enable_register,
                 uint8_t enable_value,
                 bool skip_pwm_enable,
                 int max_value,
                 bool skip_chip_config);
    ~I2CPwmOutput() override;

    bool init() override;
    bool setBrightness(int brightness) override;
    int getCurrentBrightness() override;
    std::string getType() const override;

private:
    bool configureMpq3367();          // optional, gated by skip_chip_config_
    bool enablePwm();                  // optional, gated by skip_pwm_enable_
    bool writeI2cByte(uint8_t slave_addr, uint8_t reg, uint8_t value);

    std::string device_;
    uint8_t address_;                  // PWM slave (e.g. 0x77 i2c-tiny-usb-pwm)
    uint8_t duty_register_;            // typically 0x00
    uint8_t enable_register_;          // typically 0x01
    uint8_t enable_value_;             // typically 0x01
    bool skip_pwm_enable_;             // when true, don't write enable_register at init
    int max_value_;                    // typically 255 (8-bit)
    bool skip_chip_config_;            // when true, don't init MPQ3367

    int fd_;
    int current_brightness_;
    int last_native_value_;            // for write coalescing
};

std::unique_ptr<OutputInterface> createI2CPwmOutput(const std::string& device,
                                                    uint8_t address,
                                                    uint8_t duty_register,
                                                    uint8_t enable_register,
                                                    uint8_t enable_value,
                                                    bool skip_pwm_enable,
                                                    int max_value,
                                                    bool skip_chip_config);

} // namespace als_dimmer

#endif // ALS_DIMMER_I2C_PWM_OUTPUT_HPP
